


/* INSERINDO NA TABLE DE USUARIO */
INSERT INTO T_SPM_USUARIO(CD_USUARIO, NM_COMPLETO, DS_LOGIN, DS_SENHA) VALUES
(1, 'MARCO ANTONIO B.', 'MARCO', '123');


/* INSERINDO NA TABELA DESTINO */
INSERT INTO T_SPM_DESTINO(CD_DESTINO, NM_DESTINO, DS_DISTANCIA) VALUES
(1, 'SÃO PAULO', 20000.00);
INSERT INTO T_SPM_DESTINO(CD_DESTINO, NM_DESTINO, DS_DISTANCIA) VALUES
(2, 'CABO FRIO - RJ', 617000.00);


/* E POR ULTIMO NA TABELA MOCHILAO, POIS ELA PRECISA DAS CHAVES PRIMARIAS DAS OUTRAS */
INSERT INTO T_SPM_MOCHILAO(CD_MOCHILAO, CD_USUARIO, CD_DESTINO, DS_ACESSORIOS, DT_PARTIDA) VALUES
(1, 1, 1, 'ROUPAS, NOTEBOOK, CADERNO, ESTOJO, CARREGADORES, GARRAFA DE AGUA', '20/09/2019');
INSERT INTO T_SPM_MOCHILAO(CD_MOCHILAO, CD_USUARIO, CD_DESTINO, DS_ACESSORIOS, DT_PARTIDA) VALUES
(2, 1, 2, 'ROUPAS E GARRAFA DE AGUA', '20/12/2019');


/* APLICANDO O INNER JOIN APENAS PARA VER QUEM É QUE VAI PARA O DESTINO, QUANDO VAI, O QUE VAI LEVAR E A DISTANCIA DESSE DESTINO */
SELECT
    /*U.CD_USUARIO "COD. USUARIO",
    M.CD_USUARIO,
    D.CD_DESTINO,
    M.CD_DESTINO,*/
    U.NM_COMPLETO "NOME COMPLETO",
    D.NM_DESTINO "LOCAL DO DESTINO",
    M.DT_PARTIDA "DATA DA PARTIDA",
    D.DS_DISTANCIA "DISTANCIA DO DESTINO"
    FROM T_SPM_USUARIO U INNER JOIN T_SPM_MOCHILAO M ON (U.CD_USUARIO = M.CD_USUARIO) INNER JOIN T_SPM_DESTINO D ON (D.CD_DESTINO = M.CD_DESTINO) ORDER BY M.DT_PARTIDA;

COMMIT;